services:
  db:
    image: postgres:16.8-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    image: tli/producer:0.0.1
    build: producer/
    container_name: producer
    ports:
      - "8080:80"
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USER=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - APP_RABBITMQ_QUEUE=fila
      - APP_PAYMENTS_INITSTATUS=PROCESANDO

  consumer:
    image: tli/consumer:0.0.1
    build: consumer/
    container_name: consumer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USER=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - APP_RABBITMQ_QUEUE=fila

