server:
    port: 8081
spring:
    application:
        name: ^project.name^
        version: ^project.version^
        description: ^project.description^
    profiles:
        active:
            - kafka
    data:
        redis:
            host: localhost
            port: 6379
            password: "12345678"
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
    jpa:
        hibernate:
            ddlAuto: update

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    kafka:
        bootstrap-servers: "localhost:9092"
        consumer:
            group-id: "payment"
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                # spring.json.trusted.packages: "com.tli.consumer.api.models.rq.PaymentStatusRQ"
                spring.json.use.type.headers: false
management:
    endpoints:
        web:
            exposure:
                include: "*"
    enabledByDefault: false
    metrics:
        tags:
            application: ${spring.application.name}
app:
    mq:
        queue: "payment"

