server:
    port: 8081
spring:
    application:
        name: consumer
    profiles:
        active:
            - kafka
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
    jpa:
        hibernate:
            ddlAuto: update
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    kafka:
        bootstrap-servers: "localhost:9092"
        consumer:
            group-id: "payment"
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                # spring.json.trusted.packages: "com.tli.consumer.api.models.rq.PaymentStatusRQ"
                spring.json.use.type.headers: false

app:
    mq:
        queue: "payment"

