spring:
    profiles:
        active:
            - kafka
    application:
        name: ^project.name^
        version: ^project.version^
        description: ^project.description^
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
    jpa:
        hibernate:
            ddlAuto: update
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    kafka:
        bootstrap-servers: "localhost:9092"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    enabledByDefault: false
    metrics:
        tags:
            application: "${spring.application.name}"

app:
    mq:
        queue: "payment"
    payments:
        initStatus: "IN_PROCESS"

